// <auto-generated/>

using System;
using Newtonsoft.Json;

namespace RightCRM.Common.Models
{
    public class Business
    {
        [JsonProperty("ACNUM")]
        public int? BusinessID { get; set; }

        [JsonProperty("ACNAME")]
        public string CompanyName { get; set; }

        [JsonProperty("ACTYPE")]
        public string BusinessType { get; set; }

        [JsonProperty("INDUSTRY")]
        public string IndustryType { get; set; }

        [JsonProperty("SIZE")]
        public string CompanySize { get; set; }

        [JsonProperty("REVENUE")]
        public int? AnnualRevenue { get; set; }

        public int? ADD_ID { get; set; }
    }
}
